remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: "About Thorsten Gau, CTO at IBM Consulting"
description: "This site act as a landing page for Thorsten Gau, Chief Technology Office (CTO) and Distinguished Engineer at IBM Consultin Germany/Austria/Switzerland"
