remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: "Thorsten Gau"
description: "Thorsten Gau is the Chief Technology Officer (CTO) and Distinguished Engineer at IBM Consulting Germany/Austria/Switzerland"
